[package]
name = "datafusion-query-cache"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
#datafusion = "42.0.0"
datafusion =  {git = "https://github.com/apache/datafusion.git"}
futures = "0.3.31"
tokio = { version = "1.40.0", features = ["full"] }
